group=floormat/shaders

[file]
filename=shader.frag
alias=shaders/shader.frag

[file]
filename=shader.vert
alias=shaders/shader.vert

[file]
filename=lightmap.frag
alias=shaders/lightmap.frag

[file]
filename=lightmap.vert
alias=shaders/lightmap.vert
